version: 0.0
os: linux
#source: 인스턴스에 복사할 디렉터리 경로
#destination: 인스턴스에서 파일이 복사되는 위치
#overwrite: 복사할 위치에 파일이 있는 경우 대체
files:
  - source: /
    destination: /home/ubuntu/Fachive_Porject_Backend_main
    overwrite: yes

permissions:
  - object: /
    pattern: "**" #모든 파일에 대한 권한을 가짐
    owner: ubuntu #app 소유자
    group: ubuntu #group (optional) of object

#배포 이후에 수행할 스크립트

hooks:

  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu