spring:
  datasource:
    url: jdbc:mysql://facaiev2-database.ck9dnzgajauz.ap-northeast-2.rds.amazonaws.com:3306
    username: admin
    password: hjkas1541

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

    s3:
      bucket: facaiev-img
        url: https://s3.ap-northeast-2.amazonaws.com/facaiev-img

    credentials:
      access-key: AKIARZQOLJAWVBA3YTGH
      secret-key: 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
      instance-profile: true